Script started on Sun Oct 11 17:52:58 2015
warning: could not update utmp entry
blade57(1)% mal[K[K[Kls
Rubric.docx       echoc.c           pollcount.syms    printbin2.script
count.s           echoc.opc         pollcount.s~      printbinc.c
count.script      makefile          pollcountc.c      printbinc.opc
count.s~          mp2.doc           pollcountc.opc    soln
countc.c          mp2.pdf           printbin.lnx      sum10.s
echo.lnx          mp2warmup.doc     printbin.opc      sum10.script
echo.opc          mp2warmup.pdf     printbin.s        sum10c.c
echo.s            pollcount.lnx     printbin.script   sum10orig.script
echo.script       pollcount.opc     printbin.syms     syms
echo.syms         pollcount.s       printbin.s~       tiny.s
echo.s~           pollcount.script  printbin1.script  tiny.script
blade57(2)% make A=pollcount
make: `pollcount.lnx' is up to date.
blade57(3)% mtip -f pollcount.lnx
For command help, type ~?
For help on args, rerun without args
Code starts at 0x100100
Using board # 2 
~resetting board #2!

Setting console dev to COM2Console: colour EGA+ 80x25
COM1 at 0x03f8 (irq = 4) is a 16550A
COM2 at 0x02f8 (irq = 3) is a 16550A


                 Welcome to UMB Tutor for the PC
   UMB Tutor is a 32-bit protected-mode PC debugger/downloader,
       based on Linux, UMB Tutor for m68k, and remote gdb.
UMB Tutor is free software and you are welcome to distribute copies
of it under certain conditions.  There is no warranty for this program.
The copyright and warranty provisions follow the Gnu general public
license, available for view in gdb and elsewhere.  Full sources available.
--bugs, suggestions, questions to eoneil@cs.umb.edu

Exception 3 at EIP=000578f3: Breakpoint
Tutor> ~downloading pollcount.lnx
....Done.

Download done, setting EIP to 100100.
Tutor> go 100100
ABCDE
Count 0 is       1
Count 1 is      71
Count 2 is     739
Count 3 is     737
Count 4 is     738
Exception 3 at EIP=00100110: Breakpoint
Tutor> ~q 
Quit handler: 
killing process 1538 Leaving board #2
blade57(4)% exit
script done on Sun Oct 11 17:54:44 2015
